CREATE TABLE IF NOT EXISTS Roles(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      role_name varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS Account_statuses (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      constraint account_statuses_limitation UNIQUE (id, title)
);

CREATE TABLE IF NOT EXISTS Style (
                       id int GENERATED by default as identity PRIMARY KEY,
                       name varchar(100) not null,
                       description varchar(255)
);

CREATE TABLE IF NOT EXISTS Users (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       last_name varchar(100) NOT NULL,
                       first_name varchar(100) NOT NULL,
                       patronymic varchar(100),
                       date_of_birth date NOT NULL,
                       phone_number varchar(12) NOT NULL,
                       role_id int references roles(id),
                       email varchar(100) NOT NULL UNIQUE,
                       password varchar(100) NOT NULL,
                       hash_salt varchar(12) NOT NULL,
                       status int references account_statuses(id) default 1,
                       visit_date timestamp
);

CREATE TABLE IF NOT EXISTS Halls (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL ,
                       address varchar(100) NOT NULL,
                       constraint halls_limitation UNIQUE (name, address)
);

CREATE TABLE IF NOT EXISTS "Group" (
                         id int GENERATED by default as identity PRIMARY KEY,
                         name varchar(100) NOT NULL,
                         description varchar(255),
                         hall_id int references Halls(id),
                         style_id int references Style(id),
                         teacher_id int references Users(id)
);